### ISSUE TITLE
alt+s to work in the way of ctrl+tab

### ISSUE THREAD

**Issue by mstawick** [pkelleter/angular-cli-quick-switch-plugin#13]
Do you think alt+s could work like ctrl+tab, which means simply tapping alt+s once would switch to previously active file?

So you could quickly switch between html and scss files, or between html and ts.

**Comment by pkelleter** [comment]
I don't really see any real advantage over the current solution to be honest.
You would save one tap in some cases, but most of the time you probably will just be confused over what the "last active tab" was and be mad that you can not access the third file in that case.
If you just want to switch back and forth between two files you can just use ctrl+tab instead?

**Comment by mstawick** [comment]
It would be consistent with regular switching, but I get your point. 
Ctrl + tab works as long as I don't use alt + s, because then the other tab gets closed.
Thanks for the plugin!
