### ISSUE TITLE
Tabs sometimes change order while switching

### ISSUE THREAD

**Issue by shayded-exe** [pkelleter/angular-cli-quick-switch-plugin#2]
Say I have two components open next to each other. As I quick switch the first component, the following can happen:
```
a.component.html | b.component.html
a.component.scss | b.component.html
b.component.html | a.component.ts
a.component.html | b.component.html
```

I understand this is due to WebStorm's behavior of remembering where tabs were, but it would be really nice if the tabs would stay put.

I just found this plugin today and it's already been a major lifesaver for me, so I might try to tackle this myself tonight and submit a pull request.

**Comment by pkelleter** [comment]
Hey PachowStudios,
first of all thank you for your contribution. 
Yes, I have already encountered this behavior as well and found it annoying. However I have not found a solution to this issue so far - but I also have to admit, that i have not put too much effort into that direction up to this point ;)
If you manage to solve this issue I would be very happy and release a new version of it as soon as possible, so feel free to dig into it - and thank you in advance for you tries :)

**Comment by pkelleter** [comment]
after further investigation it turns out, that this issue can not be fixed easily, since it is based on the default behavior of the IDE itself
