### ISSUE TITLE
Support .sass extension

### ISSUE THREAD

**Issue by maxfahl** [pkelleter/angular-cli-quick-switch-plugin#3]
It seems that the plugin doesn't recognise scss files with the .sass-extension. Would this be easy to implement?

**Comment by pkelleter** [comment]
Hey Max,

Yeah it would be easy to implement, although originally I wanted to support arbitrary extensions (by making them configurable). Unfortunately i did not find the time to implement that yet.
If this feature is urgent to you, feel free to clone the repo and add your file-type to the array here:

https://github.com/pkelleter/angular-cli-quick-switch-plugin/blob/master/src/main/java/QuickSwitchAction.java

You can then add your custom build to your IDE without the need of publishing it to the IntelliJ Repository.

**Comment by maxfahl** [comment]
Thank you for a quick answer. I will do just that!

**Comment by pkelleter** [comment]
Support for sass files has been added and will be included in the next release.
Unfortunately configurable extensions will still not be part of the next release though.
